import { ChapterMark, Diamond } from "./Ornaments";

/**
 * FAQ as a hand-set Q&A book. Uses native <details>/<summary> so the
 * accordion is fully keyboard-accessible and works without JS. The marker
 * is a custom rotating diamond, not a chevron — keeps the editorial voice.
 */

type Qa = { q: string; a: string };

const FAQS: Qa[] = [
  {
    q: "Is the app free?",
    a: "Yes. Every shloka, every translation, and the chat with Krishna Ji are available freely. The Pilgrim membership simply removes the brief sponsor messages between chapters and helps fund the daily verse for everyone else.",
  },
  {
    q: "How is this different from reading the Gita online?",
    a: "Three things. First, the reading discipline — each section is ticked as you read it, so you cannot skim a verse. Second, the conversation — you can ask Krishna Ji a question and receive a reply rooted in a specific shloka. Third, the daily verse — a single line arrives each morning to anchor your day.",
  },
  {
    q: "Are the translations trustworthy?",
    a: "The Hindi master text is hand-curated. Translations into the other twenty languages are produced with Gemini's translation model, then reviewed for tone, register, and reverence before release. We update them whenever a reader flags a phrase that could be improved.",
  },
  {
    q: "Does Krishna Ji's reply use AI?",
    a: "Yes. The replies are generated by a language model that is constrained to Gita-rooted answers — every response includes the specific chapter and verse it grew from, so you can read the original yourself.",
  },
  {
    q: "Is my conversation private?",
    a: "Your conversations are stored privately under your account and used only to give you continuity across sessions. We do not sell them, and we do not use them to train any third-party model.",
  },
  {
    q: "Will there be an iOS version?",
    a: "An iOS release is planned after the Android launch settles. Join the daily verse on Android in the meantime, or write in if you would like to be notified directly.",
  },
];

export const Faq = () => {
  return (
    <section
      aria-label="Frequently asked questions"
      className="relative bg-parchment-warm/40 py-24 lg:py-32"
    >
      <div className="absolute inset-x-0 top-0 h-px bg-ink/15" />
      <div className="absolute inset-x-0 bottom-0 h-px bg-ink/15" />

      <div className="mx-auto max-w-canvas px-6 lg:px-10">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-12 lg:gap-16">
          {/* Left — sticky header */}
          <div className="lg:col-span-4">
            <div className="lg:sticky lg:top-20">
              <div className="mb-5 flex items-center gap-3 text-gold-deep">
                <ChapterMark className="h-5 w-auto" />
                <span className="eyebrow">Chapter VIII · Questions</span>
              </div>
              <h2 className="font-display text-display-md font-bold text-balance text-ink-deep">
                Questions
                <br />
                <span className="italic text-saffron">that arrive.</span>
              </h2>
              <p className="mt-6 max-w-xs text-lg leading-relaxed text-ink-soft">
                Eight that arrive most often. If yours is not here, write in &mdash;
                we read every letter.
              </p>
            </div>
          </div>

          {/* Right — accordion */}
          <ol className="lg:col-span-8">
            {FAQS.map((qa, idx) => (
              <li key={idx}>
                <details
                  className="group border-t border-ink/20 py-6 first:border-t-0"
                  // open the first by default so visitors see how it works
                  open={idx === 0}
                >
                  <summary className="flex cursor-pointer list-none items-start justify-between gap-6 outline-none focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-saffron">
                    <span className="flex items-start gap-5">
                      <span className="mt-1 font-mono text-sm font-bold text-gold-deep">
                        {String(idx + 1).padStart(2, "0")}
                      </span>
                      <span className="font-display text-2xl font-semibold text-ink-deep transition-colors group-hover:text-saffron-deep md:text-[1.65rem]">
                        {qa.q}
                      </span>
                    </span>
                    {/* Custom marker — rotating diamond, not a chevron */}
                    <span className="mt-2 inline-flex items-center justify-center">
                      <Diamond
                        size={9}
                        className="text-gold transition-transform duration-500 group-open:rotate-[135deg]"
                      />
                    </span>
                  </summary>
                  <div className="mt-4 pl-10">
                    <p className="max-w-xl text-[1.05rem] leading-relaxed text-ink-soft md:text-[1.125rem]">
                      {qa.a}
                    </p>
                  </div>
                </details>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </section>
  );
};
